config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'miniblog#index'  #ルートパスの指定
  # get 'miniblog' => "miniblog#index"
  resources :miniblog
  get 'mypage/:id' => "mypage#show"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
  validates :text, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :text, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/miniblog_controller.rb
class MiniblogController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Tweet.includes(:user)
  end

  def new
  end

  def create
    tweet = tweet_params.merge(user_id: current_user.id)
    success_flag = Tweet.create(tweet).valid?
    @status = success_flag ? "成功": "失敗"
  end

  def edit
    @tweet = Tweet.find(params[:id])
    redirect_to(action:"index") unless current_user.id == @tweet.user_id
  end

  def update
    tweet = Tweet.find(params[:id])
    if current_user.id == tweet.user_id
      success_flag = tweet.update(tweet_params)
      @status = success_flag ? "成功": "失敗"
    else
      redirect_to action:"index"
    end
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  def destroy
    tweet = Tweet.find(params[:id])
    if current_user.id == tweet.user_id
      success_flag = tweet.destroy
      @status = success_flag ? "成功": "失敗"
    else
      redirect_to action:"index"
    end
  end

  private
  def tweet_params
    params.permit(:text)
  end


end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @tweets = user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/miniblog_helper.rb
module MiniblogHelper
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div>
        <h1><%= link_to "miniblog", "/" %></h1>
        <% if user_signed_in? %>
          <div>
            <%= link_to "マイページ", "/mypage/#{current_user.id}" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            <%= link_to "投稿する", new_miniblog_path %>
          </div>
        <% else %>
          <div>
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        <% end %>
      </div>
      <hr>
    </header>
    <%= yield %>
  </body>
</html>

app/views/miniblog/create.html.erb
<h2>記事作成に<%= @status %>しました。</h2>
<%= link_to "OK", "/" %>

app/views/miniblog/destroy.html.erb
<h2>記事削除画面</h2>
記事削除に<%= @status%>しました。
<%= link_to "OK", "/miniblog" %>

app/views/miniblog/edit.html.erb
<h2>ツイート編集画面</h2>
<%= form_tag("/miniblog/#{@tweet.id}", method: :put) do %>
  <textarea cols="30" name="text" placeholder="text" rows="10"><%= @tweet.text %></textarea>
  <input type="submit" value="UPDATE">
  CANSELL
<% end %>

app/views/miniblog/index.html.erb
<% @posts.each do |post| %>
  <div>
    <p>
      <span><%= post.user.nickname %>：</span>
      <%= post.text %>
      <%= link_to "SHOW", "/miniblog/#{post.id}" %>
      <% if user_signed_in? && current_user.id == post.user_id %>
        <%= link_to "EDIT", "/miniblog/#{post.id}/edit" %>
        <%= link_to "DELETE", "/miniblog/#{post.id}", method: :delete %>
      <% end %>
    </p>
  </div>
<% end %>

app/views/miniblog/new.html.erb
<h2>記事投稿画面</h2>
<h2>form_tag</h2>
<%= form_tag('/miniblog', method: :post) do %>
  <textarea cols="30" name="text" placeholder="text" rows="10"></textarea>
  <input type="submit" value="SENT">
<% end %>

<h2>form_with</h2>
<%= form_with(url: "/miniblog", local: true) do |form| %>
  <%= form.text_area :text %>
  <%= form.submit %>
<% end %>

app/views/miniblog/show.html.erb
<h2>記事詳細ページ</h2>
<div>
  <p>
    <span><%= @tweet.user.nickname %>：</span>
    <%= @tweet.text %>
    <% if user_signed_in? && current_user.id == @tweet.user_id %>
      <%= link_to "EDIT", "/miniblog/#{@tweet.id}/edit" %>
      <%= link_to "DELETE", "/miniblog/#{@tweet.id}", method: :delete %>
    <% end %>
  </p>
</div>

app/views/miniblog/update.html.erb
<h2>記事更新確認画面</h2>
記事の更新に<%= @status %>しました

app/views/mypage/show.html.erb
<h2><%= @nickname %>のページ</h2>
<% @tweets.each do |tweet| %>
  <div>
    <p>
      <%= tweet.text %>
      <%= link_to "SHOW", "/miniblog/#{tweet.id}/" %>
      <% if user_signed_in? && current_user.id == tweet.user_id %>
        <%= link_to "EDIT", "/miniblog/#{tweet.id}/edit" %>
        <%= link_to "DELETE", "/miniblog/#{tweet.id}", method: :delete %>
      <% end %>
    </p>
  </div>
<% end %>